version: '3'

services:
  master:
    build:
      context: ./master
    container_name: master
    ports:
      - "25000:25000"
    environment:
      - SECONDARY_URLS=http://secondary1:5001,http://secondary2:5002
    command: python master.py

  secondary1:
    build:
      context: ./secondary
    container_name: secondary1
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    command: python secondary.py

  secondary2:
    build:
      context: ./secondary
    container_name: secondary2
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
    command: python secondary.py
